name: nvim-protoc-buildx
on:
  push:
    tags:
      - nvim*-protoc*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Tag Name
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "nvim(?<nVersion>.*)-protoc(?<pVersion>.*)"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yuchanns/nvim:${{ steps.tagName.outputs.nVersion }}-protoc${{ steps.tagName.outputs.pVersion }}
          platforms: linux/amd64,linux/arm64
          file: ./nvim.protoc.Dockerfile
          context: .
          build-args: NVIM_VERSION=${{ steps.tagName.outputs.nVersion }},PROTOC_VERSION=${{ steps.tagName.outputs.pVersion }}
